web:
  container_name: BMP
  build: maxsim/docker/
  ports:
    - "80:80"
  volumes:
    - .:/var/www/html
    - ./maxsim/log:/var/log/apache2
  labels:
    - "traefik.http.routers.bmp.rule=Host(`bmp.localhost`)"